[package]
name = "osm"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = ["Win32_System_Com"] }
windows-core = "0.62.2"
osm-proc-macros = { path = "../osm-proc-macros" }
